image: node:latest

stages:          # List of stages for jobs, and their order of execution
  - lint

spectral-linting:   # This job also runs in the test stage.
  stage: lint    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Linting API Designs."
    - npx @stoplight/spectral-cli lint ./reference/**/*.{json,yml,yaml} -r .spectral.json -o test-results/spectral-results.xml -f junit
  artifacts:
    when: always
    reports:
      junit:
        - test-results/spectral-results.xml
